# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: arpir
nom_equipe: teammch
code_equipe: 1f

theme: jekyll-theme-dinky
